### ISSUE TITLE
Trying to get Interactive to work

### ISSUE THREAD

**Issue by MrMonotone** [sebashwa/phaser-plugin-isometric#3]
Interactive does not seem to work. It seems to set the bounds of the object at half its actual size. 

This is the following code I have been using. if you want the whole assets I can provide. Everything renders properly just the interaction occurs only in 1/4 of the tile.

```
  spawnTiles() {
    var tile;
    for (var xx = 0; xx < 256; xx += 38) {
        for (var yy = 0; yy < 256; yy += 38) {
            tile = this.add.isoSprite(xx, yy, 0, 'tile', this.isoGroup);
            tile.setInteractive();
            tile.on('pointerover', function () {

              this.setTint(0x86bfda);
      
            });
            tile.originX = 0.5;
            tile.originY = 0.0;
        }
    }
}
```

**Comment by MrMonotone** [comment]
The problem can be more easily seen with the unproject function. Even if you try to fix the unproject function the way the project function is it says that the start of the map area is in the negatives when it should be zero. I am comparing to http://www.rotates.org/phaser/iso/examples/interaction.htm

The left corner of the map the pixel when unprojected is 0 in the link above. In this project it is -19 I thinl.

**Comment by MrMonotone** [comment]
It seems like there is some inconsistency between where the object is rendered and where the object thinks it is in the world. I drew the corners on the map using the body debugrender function. 
![isoproblem](https://user-images.githubusercontent.com/931315/42184046-e463d7f2-7df8-11e8-88af-db0bae14de22.PNG)

EDIT: This seems to be happening because of setting the origin.
EDIT2: The bottom white squares are where the points are actually being projected to. The rendering is not the same. They should be the same I just do not know which is wrong. I am assuming that the projection is wrong some way

Any advice on solving I would appreciate!

**Comment by sebashwa** [comment]
Sorry I was not available the past week or so. :beach_umbrella: Thanks for the extensive bug report! I'll try to look into it as soon as possible

**Comment by sebashwa** [comment]
Hey @MrMonotone,

sorry for this very late reply!

The reason why there is an offset is indeed because you change the origin of your tile sprite in your code here:

```
tile.originX = 0.5;
tile.originY = 0.0;
```

It is by default set to the middle of the sprite. Check [this](https://github.com/photonstorm/phaser/blob/d3181b41c5fe5960fc6fec709d933fd1bdddca10/src/gameobjects/components/Origin.js#L41) out! Reseting the origin introduces this offset and is the reason why the interaction feels wrong.
If you want to change the position of your sprite, use the `isoX`, `isoY` and `isoZ` properties.

I added a new example, which resembles the one you are approaching here. Check out the [code](https://github.com/sebashwa/phaser3-plugin-isometric/blob/master/docs/src/IsoInteractionExample.js) and the [running example](https://sebashwa.github.io/phaser3-plugin-isometric/pages/interaction_example.html)

Hope this helps!

Cheers
